api/api/urls.py
from django.contrib import admin
from django.urls import path, include

api_urls = [
    path('a1/', include('calculate.urls'))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(api_urls)),
    path('', include('webapp.urls')),
]

api/calculate/urls.py
from django.urls import path
from . import views

app_name = 'calculate'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('substarct/', views.subtract, name='subtract'),
    path('multiply/', views.multiply, name='multiply'),
    path('divide/', views.divide, name='divide'),
]

api/webapp/urls.py
from django.urls import path
from webapp.views import Index

urlpatterns = [
    path('', Index.as_view(), name='index'),
]

api/calculate/models.py
from django.db import models

# Create your models here.

api/webapp/models.py
from django.db import models

# Create your models here.

api/calculate/views.py
import json
from django.http import JsonResponse, HttpResponse, HttpResponseNotAllowed
from django.views.decorators.csrf import ensure_csrf_cookie


@ensure_csrf_cookie
def get_token_view(request, *args, **kwargs):
    if request.method == 'GET':
        return HttpResponse()
    return HttpResponseNotAllowed(['GET'])

def add(request):
    if request.method == "POST":
        data = json.loads(request.body)
        if 'A' in data and 'B' in data:
            try:
                result = int(data['A']) + int(data['B'])
                return JsonResponse({'result': result})
            except:
                return JsonResponse({'error': 'Invalid input'}, status=400)
        else:
            return JsonResponse({'error': 'No data provided'}, status=400)


def subtract(request):
    if request.method == "POST":
        data = json.loads(request.body)
        if 'A' in data and 'B' in data:
            try:
                result = int(data['A']) - int(data['B'])
                return JsonResponse({'result': result})
            except:
                return JsonResponse({'error': 'Invalid input'}, status=400)
        else:
            return JsonResponse({'error': 'No data provided'}, status=400)


def multiply(request):
    if request.method == "POST":
        data = json.loads(request.body)
        if 'A' in data and 'B' in data:
            try:
                result = int(data['A']) * int(data['B'])
                return JsonResponse({'result': result})
            except:
                return JsonResponse({'error': 'Invalid input'}, status=400)
        else:
            return JsonResponse({'error': 'No data provided'}, status=400)


def divide(request):
    if request.method == "POST":
        data = json.loads(request.body)
        if 'A' in data and 'B' in data:
            try:
                result = int(data['A']) / int(data['B'])
                return JsonResponse({'result': result})
            except:
                return JsonResponse({'error': 'Invalid input'}, status=400)
        else:
            return JsonResponse({'error': 'No data provided'}, status=400)

api/webapp/views.py
from django.shortcuts import render
from django.views import View


class Index(View):
    def get(self, request):
        return render(self.request, 'index.html')

api/webapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Калькулятор</title>
</head>
<body>
    <h1>Калькулятор</h1>
    <div id="inp">
        <input type="text" name="one">
        <input type="text" name="two">
    </div>

    <div id="btn">
        <button data-new="{% url 'calculate:add' %}" value="add" onclick="op='+'">+</button>
        <button data-new="{% url 'calculate:subtract' %}" value="subtract" onclick="op='-'">-</button>
        <button data-new="{% url 'calculate:multiply' %}" value="multiply" onclick="op='*'">*</button>
        <button data-new="{% url 'calculate:divide' %}" value="divide" onclick="op='/'">/</button>
    </div>

    <div id="res">
        <h1 id="result"></h1>
    </div>

    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>